version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
      - dependency-name: '@react-native/metro-config'
        versions: ['0.73.0']
    labels:
      - 'bot'
    groups:
      weekly-updates:
        patterns:
          - '*'
