name: CI/CD workflow for Next.js with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Node.js for Next.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies for Next.js
    - name: Install Next.js dependencies
      run: npm install

    # Build Next.js project
    - name: Build Next.js
      run: npm run build

    # SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1.9
      with:
        args: >
          -Dsonar.organization=divatech-dz
          -Dsonar.projectKey=Divatech-dz_Erp
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

