name: CI/CD workflow for Maven Build and Sonar Code Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Debugging to list the directory structure
      - name: List files for debugging
        run: ls -R

      # Maven build step
      - name: Build with Maven
        run: mvn clean install -f pom.xml

      # SonarQube Scan - this should run on both push and pull request
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v1.9
        with:
          args: >
            -Dsonar.organization=divatech-dz
            -Dsonar.projectKey=Divatech-dz_Erp
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
