name: CI/CD workflow for Next.js with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js for Next.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Install dependencies for Next.js
    - name: Install Next.js dependencies
      run: npm install

    # Step 4: Build Next.js project
    - name: Build Next.js
      run: npm run build

    # Step 5: Set up JDK 17 (Explicit Java Home)
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    # Explicitly set JAVA_HOME to ensure Java 17 is used
    - name: Set Java 17 as default
      run: echo "JAVA_HOME=/opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17/x64" >> $GITHUB_ENV

    # Step 6: SonarQube Scan
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1.9
      with:
        args: >
          -X
          -Dsonar.organization=divatech-dz
          -Dsonar.projectKey=Divatech-dz_Erp
          -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
          -Dsonar.pullrequest.branch=${{ github.head_ref }}
          -Dsonar.pullrequest.base=${{ github.base_ref }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL:${{secrets.SONAR_HOST_URL}}
        JAVA_HOME: /opt/hostedtoolcache/Java_Temurin-Hotspot_jdk/17/x64  # Ensuring JDK 17 path
