name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        projectBaseDir: .
        extraProperties: |
          sonar.projectKey=Divatech-dz_Erp
          sonar.projectName=Erp
          sonar.projectVersion=1.0
          sonar.sources=.
          sonar.sourceEncoding=UTF-8
          sonar.exclusions=**/__tests__/**/*, **/*.test.js
          sonar.tests=__tests__
          sonar.javascript.file.suffixes=.js,.jsx,.ts,.tsx
          sonar.typescript.lcov.reportPaths=coverage/lcov-report/lcov.info
